# Generated by Django 4.2.5 on 2023-09-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastrarUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=128, verbose_name='Sobrenome')),
                ('data_nascimento', models.DateField(verbose_name='Data_Nascimento')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('senha', models.CharField(max_length=36, verbose_name='<PASSWORD>ha')),
            ],
        ),
    ]
